### ISSUE TITLE
BCP 101 is a concatenation

### ISSUE THREAD

**Issue by jlivingood** [IASA2/draft-ietf-iasa2-struct#10]
BCP 101 is a concatenation of several docs, which is super confusing IMO. 

At root it is RFC 4071 - Structure of the IETF Administrative Support Activity (IASA). 

But RFC 4071 is also updated by RFC 4371 - BCP 101 Update for IPR Trust
and
RFC 7691 - Updating the Term Dates of IETF Administrative Oversight Committee (IAOC) Members

References:
https://tools.ietf.org/html/bcp101
https://tools.ietf.org/html/rfc4071
https://tools.ietf.org/html/rfc4371
https://tools.ietf.org/html/rfc7691

**Comment by jlivingood** [comment]
I think RFC 7691 is easily handled, because IAOC goes away, so structure needs to have an OBSOLETES statement for 7691.

**Comment by jlivingood** [comment]
I think RFC 4371 is also handled, because of Jari's update of the Trust document at https://datatracker.ietf.org/doc/draft-ietf-iasa2-trust-update/. 

So I think we need a statement as well that probably says that structure OBSOLETES 4371 **or** we don't have a statement in the header on 4371 since Jari's Trust doc will update/obsolete 4371.

ACTION: Ask Jari if the trust update needs to obsolete 4371 rather than update it. Not sure.

**Comment by josephlhall** [comment]
I'm going to go with having Jari's obsolete 4371... will leave this open.

**Comment by josephlhall** [comment]
We should ping Jari on this. The latest version of his trust draft updates 4371 and this 4071bis draft says (in the text, not in the document metadata) that it "replaces" 4371. I'm going to change the text to say that it obsoletes 4071 and then leave a marker for this issue... I don't think we can obsolete 4371 with a 4071bis, right? I mean that would require more text and Jari should just do that in his draft.

**Comment by jlivingood** [comment]
Correct!

**Comment by josephlhall** [comment]
this is fixed by the header
