### ISSUE TITLE
Explain IETF ED in Sec 3

### ISSUE THREAD

**Issue by jlivingood** [IASA2/draft-ietf-iasa2-struct#17]
Alissa:

I believe the change in titles should be explained in Section 3 of draft-ietf-iasa2-struct

Russ

l
On Nov 10, 2018, at 11:03 AM, Alissa Cooper <alissa@cooperw.in> wrote:

Hi John,

The role of executive director is defined in the LLC agreement: https://www.ietf.org/documents/180/IETF-LLC-Agreement.pdf

Best,
Alissa

On Nov 10, 2018, at 3:23 PM, John C Klensin <john-ietf@jck.com> wrote:

Russ,

Thanks _very_ much for the explanation and the pointers.  I
obviously stand corrected.

Two suggestions:

(1) Shuffling terminology and titles around this way is very
confusing, especially to those who have not been paying careful
attention.  I have evidence (so far only in offlist
conversations) that at least some people who have been very
active in the WG are either confused or are describing the
situation in a way that adds to the confusion.   Even using
"Executive Director of the IETF LLC" and "Managing Director of
the IETF Secretariat" and dropping "IETF Executive Director"
entirely would help a lot.  Given our claimed preference for
avoiding royalty of various sorts, it might be even better to
get rid of "Executive Director" (a title that predates IASA and
goes back to a time when the IETF did not control its
administrative arrangements except by persuasion and requests
entirely).

(2) The idea that the best reference (if that is in fact the
case) for where these titles are nailed down is a link to an
archived email message is a little scary.  IMO, these titles (or
whatever is picked) should be defined and explained in an RFC or
something destined for RFC Publication.  Probably the
definitions should be cited in any document in which there is a
possibility of confusion, but, in any case, the definitions
should be part of our formal archival record.  Are  they in one
of the WG documents I haven't read carefully enough yet?

best,
  john

--On Saturday, November 10, 2018 02:11 -0500 Russ Housley
<housley@vigilsec.com> wrote:

John:

I confirmed that the references to "IETF Executive Director"
in draft-ietf-iasa2-rfc4844-bis-00 are referring to the
Executive Director of the IETF LLC, not the previous use of
that title.

These terms are nailed dow here:
https://mailarchive.ietf.org/arch/msg/iasa20/C0g-Gp4vbGMYsGW-t
FXmxQAKAgQ
<https://mailarchive.ietf.org/arch/msg/iasa20/C0g-Gp4vbGMYsGW-
tFXmxQAKAgQ>

In summary:
- IASA 2.0 replaces the role of IETF Administrative Director
(IAD) with the new role of IETF Executive Director. - The
title of IETF Executive Director has previously been used by
Alexa Morris; Alexa will now be known as the Managing
Director, IETF Secretariat. - Portia Wenze-Danley, will serve
as Interim IETF Executive Director reporting to the LLC Board
of Directors.

Russ

On Nov 9, 2018, at 9:12 PM, John C Klensin
<john-ietf@jck.com> wrote:

Hi.

In the process of checking documents to see where a
consolidating update might be a better idea than completely
replacing earlier ones, I noticed that, while
draft-ietf-iasa2-rfc4844-bis-00 eliminates references to the
IAOC (as the cover note and Section 7 say it does), it still
contains references to the IETF Executive Director.  The
tracker says it is in WG Last Call, so...

It hence either needs another revision or should be collapsed
into a consolidated update document.  One argument for the
latter is that, as described in Section 7, this draft makes
changes --whether characterized as "minor editorial" or not--
that are not strictly necessary to fix the document for the
IASA2 changes and hence lie outside the WG's Charter.  Authors
of these replacement documents have a dilemma in that regard:
if they stay within the charter, they need to just make the
IASA2 changes, which means ignoring all errata, editorial
changes motivated by the passage of time, etc.  That would
leave a replacement document for which changes to the earlier
one that we know are needed have not been applied.   Or they
can make the changes and risk some sorehead complaining
during IETF Last Call that the WG didn't do a good job of
reviewing documents, violated its charter, etc., and that any
documents should be subject to the sort of review and
discussion we'd consider reasonable for something that might
--intentionally or inadvertently-- may making changes to
fundamental processes. Speaking as a candidate for the
sorehead role, the WG should certainly not assume the latter
won't happen.

  best,
   john

_______________________________________________
iasa20 mailing list
iasa20@ietf.org
https://www.ietf.org/mailman/listinfo/iasa20

_______________________________________________
iasa20 mailing list
iasa20@ietf.org
https://www.ietf.org/mailman/listinfo/iasa20

**Comment by jlivingood** [comment]
Andrew wrote:

I observe that the ED is not only outlined in the LLC agreement, but is
already in fact discussed in -struct, in section 4.4.  I can see an
argument for highlighting this change in section 3. But I don't think it's
unreasonable to expect people to look over the table of contents and note
the important terms there, also. That there's a whole section on the
relationship between the ED and the LLC Board ought to make it plain
something is perhaps changed in familiar terms.

**Comment by josephlhall** [comment]
I think the edits I've just committed deal with this but it would be worthwhile to go through and make sure it is 1) very clear and 2) super-duper consistent within the doc and across to the operating agreement.

**Comment by josephlhall** [comment]
We mention this in a few places. We'll need to make sure it is crystal clear, but closing for now,.
