### ISSUE TITLE
Mention RFC 4089

### ISSUE THREAD

**Issue by jlivingood** [IASA2/draft-ietf-iasa2-struct#18]

**Comment by jlivingood** [comment]
or update / replace

**Comment by josephlhall** [comment]
Klensin seems to be working on getting 4089 historic status? https://mailarchive.ietf.org/arch/msg/iasa20/bKXeerTt1ues0Wx2K8wLyv3s6YU

**Comment by jlivingood** [comment]
No need to mention RFC 4089 in this doc.

BUT - will add WG note to ask RFC Editor to make 4089 historic after this doc is approved.
