### ISSUE TITLE
transition stuff, should it stay?

### ISSUE THREAD

**Issue by josephlhall** [IASA2/draft-ietf-iasa2-struct#19]
When this was more of a document describing the work of the IASA2 WG, it felt important to have the transition sections and such... but now they seem a bit out of place for a BCP. Wondering if they seem out of place to others and if so what to do about it?

**Comment by jlivingood** [comment]
Any orphan bits could always move to the doc Brian is managing -- https://datatracker.ietf.org/doc/draft-haberman-iasa20dt-recs/ ??

**Comment by josephlhall** [comment]
I'm going to put a pin in this... some of this stuff seems important so my first reaction to just delete it seems to crass. @coopdanger can I get you to look at this when you do your review? I'll mark it as a TODO in the text.

**Comment by jlivingood** [comment]
I reflected on the transition section at the end. I don’t think this belongs here – we should consider moving it to Brian’s design team recommendations document IMO. We look forward to your thoughts on that.

**Comment by jlivingood** [comment]
It is gone...
