### ISSUE TITLE
ISOC BoT as ultimate step in appeals process still relevant?

### ISSUE THREAD

**Issue by josephlhall** [IASA2/draft-ietf-iasa2-struct#23]
In copying over the appeals process from 4071 it says (currently in section 3.7), "If he or she is not satisfied with the IAB response, he or she can escalate the issue to the ISOC Board of Trustees, as described in [RFC2026]." Is that still right? Do we still expect the ISOC BoT to serve this function?

**Comment by coopdanger** [comment]
Yes, that is still correct.

**Comment by josephlhall** [comment]
Awesome, thanks.
