### ISSUE TITLE
IRTF Issue

### ISSUE THREAD

**Issue by jlivingood** [IASA2/draft-ietf-iasa2-struct#97]
> On the high level principle this would be fine. However, it makes me ask the first question if IRSG is the right entity. It likely are, but I lack the insight into IRTF management to say that. Secondly, this will be the first mention of the IRSG in the document. So some introduction or at least reference appears to be needed. 

[JL] I am not sure why we’d say IRSG instead of just IRTF, which is what we already say in 4.1 under the definition for the IETF LLC. Thus, my preference is IRTF (see below) to keep it simple & consistent. I think this also means we need to add the IRTF to the terminology section in 4.1.

The IETF LLC Board is directly accountable to the IETF community for
   the performance of the IASA 2.0.  However, the nature of the Board's
   work involves treating the IESG, IRTF, and IAB as major internal customers
   of the administrative support services.  The Board and the IETF
   Executive Director should not consider their work successful unless
   the IESG, IRTF, and IAB are also satisfied with the administrative support
   that the IETF is receiving.

**Comment by josephlhall** [comment]
fixed by f9dc07ee4c99f4c8060f66264c0c409f9590d27c
